# Generated by Django 3.0.5 on 2020-04-20 06:54

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('picture', models.FileField(blank=True, default='default_photo.jpg', null=True, upload_to=cars.models.upload_path)),
            ],
        ),
    ]
